[workspace]
members = [
    "crates/revelation",
    "crates/leviticus",
    "crates/epiphany",
    "crates/elder",
    "crates/loi", 
    "crates/vfs", 
    "crates/monitor", 
    "crates/cli", 
    "crates/leaven", 
    "crates/gideon", 
    "crates/passover", 
]

resolver = "2"

# [patch.crates-io]
# inkwell = { path = "../inkwell-patched" }
