[package]
name = "vfs"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
cli = { path = "../cli" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.75"
serde-wasm-bindgen = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.150"
async-trait = "0.1.89"
js-sys = "0.3.102"
futures = "0.3.32"
web-sys = { version = "0.3", features = ["console"] }
tokio = "1.52.3"
clap = "4.6.1"
