use std::sync::{Arc, RwLock};

use crate::{
    compiler::{config::CompileConfig, engine::CompileEngine, state::CompileState},
    context::Context,
    kernel::Kernel,
};

// # 1. Separation of Concerns
// - Config: Static, immutable information (paths, project names).
// - State: The volatile, runtime truth of your system (what has been compiled, what is dirty).
// - Context: The environment (user settings, logging handles, temporary buffers).
// - Engine: The "Doer." It doesn't need to know *what* the Kernel is doing; it just needs the tools to process the code.
// - Kernel: The "Orchestrator." It manages the high-level flow and bridges the Environment (`Context`) with the Work (`Engine`).

pub fn init() -> Kernel {
    // 1. Create the Shared Environment (Dependencies)
    // Wrap them in Arc so multiple pipelines/threads can own them.
    let context = Arc::new(Context::new());

    // We use RwLock for state and config so components can
    // read/write them at runtime (e.g., REPL changing root)
    let config = Arc::new(RwLock::new(CompileConfig::default()));
    let state = Arc::new(RwLock::new(CompileState::default()));

    // 2. Build the Engine
    // The engine receives the shared pointers, not the raw data.
    let engine = CompileEngine::new(context.clone(), config, state);

    // 3. Build the Kernel
    // The kernel orchestrates the engine and context.
    let kernel = Kernel::new(context, engine);

    kernel
}

pub fn init2() -> Kernel {
    let context = Arc::new(Context::new());
    let config = Arc::new(RwLock::new(CompileConfig::default()));
    let state = Arc::new(RwLock::new(CompileState::default()));
    let engine = CompileEngine::new(context.clone(), config, state);
    let kernel = Kernel::new(context, engine);
    kernel
}

// ### 1. Trait-based DI (The "Interface" layer)
// We would use a trait if you wanted to swap out the **entire** `FrontendPipeline` for a different implementation (e.g., a `WasmFrontend` vs. a `NativeFrontend`) at runtime.
// * **The Goal:** Abstraction. You define *what* a pipeline does, not *how* it does it.
// * **The Complexity:** It forces everything behind `Box<dyn Stage>` or Generics (`<T: Stage>`), which can make your code harder to read and debug.

// ### 2. Struct-based DI (The "Wiring" layer)
// We are using this to **propagate state**. Since your `Frontend`, `Middle`, and `Backend` pipelines are concrete types that *must* exist and work together, traits were actually adding "indirection" you didn't need yet.
// * **The Goal:** Connectivity. You define *how* data flows through your system.
// * **The Benefit:** It is "Type-Safe and Fast." The compiler knows exactly which struct is calling which method, and there is zero overhead from dynamic dispatch (no `dyn` overhead).

// ### Why we "abandoned" the Trait approach (for now)

// If we used a trait for every pipeline:

// Trait approach
// pub trait Pipeline { fn compile(&self); }
// let pipeline: Box<dyn Pipeline> = Box::new(FrontendPipeline::new(...));

// ...you would lose the ability to easily access the `Lexer` or `Parser` fields on the `FrontendPipeline` directly without down casting.
// Because you are building a compiler, you often need to reach into the `FrontendPipeline` to get the `AST` generated by the `Parser`.

// ### The "Hybrid" Future (The best of both worlds)

// You *can* have both. If you eventually need to support different backends (e.g., `LLVMBackend` vs `CBackend`), you use the **Struct-based DI** to handle the heavy lifting of state sharing, and use a **Trait** only for the specific stage that needs to vary.

// **Summary:** * **Struct Injection:** You are building the "Plumbing." It connects your state and configuration to every module.

// * **Trait Injection:** You are building "Plug-ins." It lets you swap out modules for different implementations.

// **Strategic Advice:** Don't reach for traits until you find yourself writing `if/else` logic to choose which pipeline to run. If your `FrontendPipeline` is always going to be *the* `FrontendPipeline`, keep using the struct-based DI. It is more performant, easier to navigate in an IDE (Go-to-Definition works perfectly), and keeps your dependency graph crystal clear.

// Does the current "Explicit Wiring" in `CompileEngine` feel too rigid, or does it feel like a relief to not have to deal with dynamic dispatch yet?
